
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GalaxyBackground from "./Galaxy/Galaxy";
import ClientOnly from "./ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cosmos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, height: '100vh', position: 'relative' }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ClientOnly>
          <GalaxyBackground />
        </ClientOnly>
        <div style={{ position: 'relative', zIndex: -999, color: 'white' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
